### ISSUE TITLE
All parent pages in breadcrumb should be links

### ISSUE THREAD

**Issue by mediajunkie** [cagov/hub.innovation.ca.gov#26]
breadcrumb trail should all work as links but the "Join us" one on this page does not: <https://innovation.ca.gov/join-us/senior-product-manager/>

[Slack Message](https://cadotgov.slack.com/archives/C02L6EAFE20/p1704211200376409?thread_ts=1704211200.376409&cid=C02L6EAFE20)

**Comment by jbum** [comment]
Working for me (navigates to https://innovation.ca.gov/join-us/), was this repaired?  Am I missing something?
