### ISSUE TITLE
Fourth-level breadcrumb

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/hub.innovation.ca.gov#36]
Right now the breadcrumb only shows 3 levels down (not counting CA.gov). This works for most pages, like[Content design principles](https://hub.innovation.ca.gov/content-design/principles/).

![Image](https://github.com/cagov/hub.innovation.ca.gov/assets/69169190/7d2b0657-f671-497b-a9fb-314173b36f20)

However, there are pages that sit under _Content design principles_. These don't show that they're child pages of _Content design principles_. One example is [Write in plain language](https://hub.innovation.ca.gov/content-design/principles/write-in-plain-language/). Note how _Content design principles_ doesn't appear in the breadcrumb string.

![Image](https://github.com/cagov/hub.innovation.ca.gov/assets/69169190/1fd4d89f-809d-4385-9d00-bff2f28121f8)

It would be helpful for the breadcrumb to show the full relationship/nesting of pages. This may be needed for #35.

**Comment by jbum** [comment]
Fixed.
