### ISSUE TITLE
Housing paper

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/hub.innovation.ca.gov#38]
Arman has written a paper about the project CalData and the Department of Housing and Community Development did together. 

- [Original version from Arman](https://docs.google.com/document/d/1SwO4FRG9sxPCFnYpx5SFBS6PvvVyv3f8KGdiNSt-DWk/edit?usp=sharing)
- [Folder of drafts](https://drive.google.com/drive/folders/12IvxiS_M9sBJT8n_ELRSfm4gxFrMN3qk)
- [Figma file](https://www.figma.com/file/mHceyAag86ji2PS2YNnfIk/Innovation-Hub-Website?type=design&node-id=4177%3A1863&mode=design&t=57VVLuI4weVo6JBX-1) where page design is taking place

**Comment by m-sullivan7** [comment]
Open items:

- [ ] Add graphics to Figma
- [ ] Create PDF version
- [ ] Accessibility remediation
- [ ] Get DOI (Arman to do)
- [ ] Get content approval from Department of Housing and Community Development (Barb to do)
- [ ] Build in Innovation Hub on a branch
- [ ] QA
- [ ] Any final approvals (Arman? Kim?)
- [ ] Publish

**Comment by zakiya** [comment]
Moved to Coda.
