### ISSUE TITLE
Introduction to plain language: remove March 7 course

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/hub.innovation.ca.gov#48]
The page lists all offerings of the course through the end of June. This issue is to remove the March 7 course once it has taken place.

**Comment by m-sullivan7** [comment]
@YeseniaGtz 

1. Am I right that it's OK for me to make these updates outside the release cadence?
2. Would you like me to make issues for them now and use the _Start date_ and _Target completion_ fields to indicate when the work will happen? Or should I make them as needed?

**Comment by YeseniaGtz** [comment]
@m-sullivan7 
1. Yes it is OK
2. If you could make those issues now it would be a great help to me, I appreciate it!

**Comment by m-sullivan7** [comment]
Thanks! All issues made.

**Comment by m-sullivan7** [comment]
Change published.
