### ISSUE TITLE
Content: ODI Strategic Goals

### ISSUE THREAD

**Issue by YeseniaGtz** [cagov/hub.innovation.ca.gov#59]
**Per Barb**

> ODI’s strategic goals need to be updated on our external website (https://innovation.ca.gov/who-we-are/our-vision/) . Please update what is there and replace with these goals. Note: Objectives are in review and not available yet. 
> 
> Director Marino has approved this request to occur now.

Goal 1 | Develop a statewide culture of innovation

Goal 2 | Embed equity in service design and delivery

Goal 3 | Build the tools and model the way for performance measurement and continuous improvement

Goal 4 | Establish a culture of operational excellence at ODI to model how a customer-centric state department can work

**Comment by m-sullivan7** [comment]
Oddly this issue was made for the Innovation Hub repo. I'm fine to use this one, but I wanted to check before I fulfilled it.

**Comment by YeseniaGtz** [comment]
@m-sullivan7 OOPs, good catch! i will move it. thank you

**Comment by YeseniaGtz** [comment]
Opened in wrong repo, moving and closing
