### ISSUE TITLE
ODI style guide: law citations

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/hub.innovation.ca.gov#74]
In writing the housing case study and technical paper, we have settled on a format for citing laws.

Short form: [Legislative body] Bill [number] ([political party]-[last name of author]-[city of author]), [title of bill]
Example: Senate Bill (SB) 35 (D-Weiner-San Francisco), Planning and Zoning: affordable housing streamlined approval process

Long form:
[Title], [chamber abbreviation]-[number], California Legislature, [legislative body], [Year]. [LegInfo URL]
Example: Planning and zoning: affordable housing: streamlined approval process, SB-35, California Legislature, Senate (2017). https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=201720180SB35
Follows Sacramento State Library guidance on [citing government/legal information](https://csus.libguides.com/c.php?g=1070490&p=9894367).

This issue is to codify this information in the ODI style guide.

**Comment by zakiya** [comment]
(For when Michael has downtime)

**Comment by m-sullivan7** [comment]
New content published.
